# -*- coding: utf-8 -*-
"""radar_nn1_4classes(v2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nO33TIOU_4nkcyRAAZEmT184MYEM9fgd
"""

# -*- coding: utf-8 -*-
"""
自测数据集（20260427）四分类雷达动作TR图识别
"""
from __future__ import annotations
import json, random, re, hashlib, shutil
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.models import MobileNet_V3_Small_Weights, mobilenet_v3_small
from torchvision.transforms import InterpolationMode
from torchvision.transforms import functional as TF

# ==== 0) Drive 挂载 ====
try:
    from google.colab import drive  # type: ignore
    drive.mount('/content/drive', force_remount=False)
except Exception:
    pass

# ==== 1) 配置 ====
DATA_ROOT = Path('/content/drive/MyDrive/Dataset_20260428_color_tr')
SAVE_DIR  = Path('/content/drive/MyDrive/iurha_runs/radar_nn1_4class(v2)')
TRAIN_RATIO, VAL_RATIO, TEST_RATIO = 18/25, 4/25, 3/25
SPLIT_SEED, REPR_PER_ACTION, REPR_FROM_SPLIT = 3407, 3, 'test'
EPOCHS, BATCH_SIZE, NUM_WORKERS = 15, 2, 2
LR, WEIGHT_DECAY, PATIENCE = 1e-4, 5e-4, 8
PIN_MEMORY, PERSISTENT_WORKERS, PREFETCH_FACTOR = True, True, 4
INPUT_SIZE, MEAN, STD, SEED = 224, 0.5, 0.5, 42
USE_IMAGENET, USE_DATA_PARALLEL, USE_AMP = True, True, True
AUX_W, THR_W, CONS_W = 0.20, 0.20, 0.08
EXTS = {'.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff', '.webp'}
PAT = re.compile(r'(.+)_person(\d+)$')
RAW2CLS = {'stand': 'stand', 'walk': 'walk', 'bend': 'bend', 'fall': 'fall'}
CLASS_ORDER = ['stand', 'walk', 'bend', 'fall']

# ==== 2) 基础工具 ====
def seed_all(seed: int = SEED):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True

def normalize(x: torch.Tensor) -> torch.Tensor:
    return TF.normalize(x, [MEAN], [STD])

def natural_key(path_or_name):
    s = path_or_name if isinstance(path_or_name, str) else Path(path_or_name).stem
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]

def unwrap_model(model: nn.Module) -> nn.Module:
    return model.module if isinstance(model, nn.DataParallel) else model

# ==== 3) 扫描与切分 ====
@dataclass
class Rec:
    path: str; cls: str; person: int; label: int; split: str

def _stable_folder_seed(folder_name: str, offset: int = 0) -> int:
    return SPLIT_SEED + int(hashlib.md5(folder_name.encode('utf-8')).hexdigest()[:8], 16) + offset

def split_one_folder(files: list[Path], folder_name: str):
    """
    使用文件夹内全部图片；固定随机打乱后，按 18:4:3 比例切分
    """
    files = sorted(files, key=natural_key)
    n = len(files)
    if n == 0:
        return [], [], []

    # 固定随机打乱，保证可复现
    idx = list(range(n))
    rng = random.Random(_stable_folder_seed(folder_name, 200003))
    rng.shuffle(idx)
    files = [files[i] for i in idx]

    # 按 18:4:3 比例切分
    n_train = max(1, int(round(n * 18 / 25)))
    n_val = max(1, int(round(n * 4 / 25)))
    n_test = n - n_train - n_val

    # 保证 test 至少 1 张（当 n>=3 时）
    if n >= 3:
        if n_test < 1:
            if n_train >= n_val and n_train > 1:
                n_train -= 1
            elif n_val > 1:
                n_val -= 1
            n_test = n - n_train - n_val

        if n_val < 1:
            if n_train > 1:
                n_train -= 1
            n_val = 1
            n_test = n - n_train - n_val

    train_files = sorted(files[:n_train], key=natural_key)
    val_files = sorted(files[n_train:n_train + n_val], key=natural_key)
    test_files = sorted(files[n_train + n_val:], key=natural_key)
    return train_files, val_files, test_files

def scan_records(root: Path):
    if not root.exists(): raise FileNotFoundError(f'未找到数据目录: {root}')
    folder_meta = []
    for d in sorted(root.iterdir()):
        if d.is_dir() and (m := PAT.fullmatch(d.name)):
            raw_cls, person = m.group(1), int(m.group(2))
            if raw_cls in RAW2CLS: folder_meta.append((d, RAW2CLS[raw_cls], person, raw_cls))
    if not folder_meta: raise RuntimeError('未找到符合要求的 stand/walk/bend/fall 相关文件夹。')
    c2i = {c:i for i,c in enumerate(CLASS_ORDER)}; i2c = {i:c for c,i in c2i.items()}
    train_recs, val_recs, test_recs, split_brief = [], [], [], {}
    for d, cls, person, raw_cls in folder_meta:
        imgs = [f for f in d.iterdir() if f.suffix.lower() in EXTS]
        tr, va, te = split_one_folder(imgs, d.name)
        split_brief[d.name] = {'raw_cls': raw_cls, 'mapped_cls': cls, 'train': len(tr), 'val': len(va), 'test': len(te), 'total': len(imgs)}
        y = c2i[cls]
        train_recs += [Rec(str(f), cls, person, y, 'train') for f in tr]
        val_recs   += [Rec(str(f), cls, person, y, 'val')   for f in va]
        test_recs  += [Rec(str(f), cls, person, y, 'test')  for f in te]
    if not train_recs or not val_recs or not test_recs: raise RuntimeError('train/val/test 中存在空集合，请检查数据。')
    return train_recs, val_recs, test_recs, c2i, i2c, split_brief

# ==== 4) 数据集 ====
class TRDataset(Dataset):
    def __init__(self, recs: list[Rec], train: bool, use_thr: bool):
        self.recs, self.train, self.use_thr = recs, train, use_thr
        self.erase = transforms.RandomErasing(p=0.10, scale=(0.02,0.08), ratio=(0.3,2.8), value=0.0)
    def _base(self, img: Image.Image) -> Image.Image:
        return TF.resize(img.convert('L'), [INPUT_SIZE, INPUT_SIZE], interpolation=InterpolationMode.BILINEAR)
    def _aug(self, img: Image.Image) -> torch.Tensor:
        img = self._base(img)
        if self.train:
            img = TF.affine(img, angle=random.uniform(-6,6), translate=(int(random.uniform(-0.03,0.03)*INPUT_SIZE), int(random.uniform(-0.03,0.03)*INPUT_SIZE)), scale=random.uniform(0.96,1.04), shear=[0.0,0.0], fill=0)
            if random.random() < 0.20: img = TF.adjust_brightness(img, random.uniform(0.9,1.1))
            if random.random() < 0.20: img = TF.adjust_contrast(img, random.uniform(0.9,1.1))
        x = normalize(TF.to_tensor(img))
        return self.erase(x) if self.train else x
    def _thr(self, img: Image.Image) -> torch.Tensor:
        a = np.array(self._base(img), dtype=np.float32) / 255.0
        thr = np.quantile(a, 0.82); a = np.where(a >= thr, a, a * 0.12); a = np.clip(a / (a.max() + 1e-8), 0, 1)
        return normalize(torch.from_numpy(a).unsqueeze(0))
    def __len__(self): return len(self.recs)
    def __getitem__(self, idx: int):
        r = self.recs[idx]; img = Image.open(r.path).convert('RGB')
        out = {'image': self._aug(img), 'label': torch.tensor(r.label, dtype=torch.long)}
        if self.use_thr: out['thr'] = self._thr(img)
        return out

# ==== 5) radar_nn1 模型 ====
class MSDW(nn.Module):
    def __init__(self, c: int):
        super().__init__(); self.dw3 = nn.Conv2d(c,c,3,1,1,groups=c,bias=False); self.dw5 = nn.Conv2d(c,c,5,1,2,groups=c,bias=False); self.bn = nn.BatchNorm2d(2*c); self.act = nn.Hardswish(); self.pw = nn.Sequential(nn.Conv2d(2*c,c,1,bias=False), nn.BatchNorm2d(c))
    def forward(self, x):
        y = self.act(self.bn(torch.cat([self.dw3(x), self.dw5(x)], dim=1))); return x + self.pw(y)

class AuxHead(nn.Module):
    def __init__(self, c: int, k: int):
        super().__init__(); self.m = nn.Sequential(nn.Conv2d(c,c,1,bias=False), nn.BatchNorm2d(c), nn.Hardswish(), nn.AdaptiveAvgPool2d(1), nn.Flatten(), nn.Dropout(0.15), nn.Linear(c,k))
    def forward(self, x): return self.m(x)

class radar_nn1(nn.Module):
    def __init__(self, num_classes: int):
        super().__init__(); weights = MobileNet_V3_Small_Weights.IMAGENET1K_V1 if USE_IMAGENET else None; base = mobilenet_v3_small(weights=weights)
        old = base.features[0][0]; new = nn.Conv2d(1, old.out_channels, old.kernel_size, old.stride, old.padding, bias=False)
        with torch.no_grad(): new.weight.copy_(old.weight.mean(dim=1, keepdim=True))
        base.features[0][0] = new; self.stem = nn.Sequential(*list(base.features[:7])); self.tail = nn.Sequential(*list(base.features[7:]))
        with torch.no_grad():
            z = torch.zeros(1,1,INPUT_SIZE,INPUT_SIZE); s = self.stem(z); t = self.tail(s); c_stem, c_tail = int(s.shape[1]), int(t.shape[1])
        self.aux = AuxHead(c_stem, num_classes); self.ms = MSDW(c_tail); self.fc1 = nn.Linear(2*c_tail, 128); self.drop = nn.Dropout(0.25); self.fc2 = nn.Linear(128, num_classes)
    def forward(self, x, need_aux: bool = False):
        s = self.stem(x); t = self.ms(self.tail(s)); gap = F.adaptive_avg_pool2d(t,1).flatten(1); gmp = F.adaptive_max_pool2d(t,1).flatten(1)
        logits = self.fc2(self.drop(F.hardswish(self.fc1(torch.cat([gap, gmp], dim=1))))); aux = self.aux(s) if need_aux else None
        return logits, aux

# ==== 6) 训练/评估 ====
def build_class_weights(recs: list[Rec], num_classes: int) -> torch.Tensor:
    cnt, total = Counter(r.label for r in recs), len(recs); w = torch.ones(num_classes, dtype=torch.float32)
    for i in range(num_classes):
        if cnt[i] > 0: w[i] = total / (num_classes * cnt[i])
    return w

def skl(a: torch.Tensor, b: torch.Tensor, T: float = 2.0) -> torch.Tensor:
    return 0.5 * (F.kl_div(F.log_softmax(a/T, dim=1), F.softmax(b/T, dim=1), reduction='batchmean') + F.kl_div(F.log_softmax(b/T, dim=1), F.softmax(a/T, dim=1), reduction='batchmean')) * (T*T)

@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, criterion, device: torch.device):
    model.eval(); total_loss = total_correct = total_n = 0; pbar = tqdm(loader, desc='Val', leave=False, dynamic_ncols=True)
    for batch in pbar:
        x = batch['image'].to(device, non_blocking=True); y = batch['label'].to(device, non_blocking=True)
        logits, _ = model(x, need_aux=False); total_loss += criterion(logits, y).item() * y.size(0); total_correct += (logits.argmax(1) == y).sum().item(); total_n += y.size(0)
        pbar.set_postfix(loss=f"{total_loss/max(total_n,1):.4f}", acc=f"{total_correct/max(total_n,1):.4f}")
    return total_loss / max(total_n,1), total_correct / max(total_n,1)

def train_one_epoch(model, loader, optimizer, scaler, criterion, device):
    model.train(); total_loss = total_correct = total_n = 0; amp_enabled = (device.type == 'cuda' and USE_AMP); pbar = tqdm(loader, desc='Train', leave=False, dynamic_ncols=True)
    for batch in pbar:
        x = batch['image'].to(device, non_blocking=True); y = batch['label'].to(device, non_blocking=True); xt = batch['thr'].to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast(device_type='cuda', enabled=amp_enabled):
            logits, aux = model(x, need_aux=True); logits_thr, _ = model(xt, need_aux=False)
            loss = criterion(logits, y) + THR_W*criterion(logits_thr, y) + AUX_W*criterion(aux, y) + CONS_W*skl(logits, logits_thr)
        scaler.scale(loss).backward(); scaler.step(optimizer); scaler.update()
        total_loss += loss.item() * y.size(0); total_correct += (logits.argmax(1) == y).sum().item(); total_n += y.size(0)
        pbar.set_postfix(loss=f"{total_loss/max(total_n,1):.4f}", acc=f"{total_correct/max(total_n,1):.4f}", lr=f"{optimizer.param_groups[0]['lr']:.2e}")
    return total_loss / max(total_n,1), total_correct / max(total_n,1)

def save_checkpoint(path: Path, model: nn.Module, c2i, i2c, split_meta):
    torch.save({'model_state': unwrap_model(model).state_dict(), 'class_to_idx': c2i, 'idx_to_class': i2c, 'input_size': INPUT_SIZE, 'image_mean': MEAN, 'image_std': STD, 'split_meta': split_meta, 'model_name': 'radar_nn1_4class'}, path)

# ==== 7) 可视化/导出 ====
def plot_curves(logs: list[dict], save_dir: Path):
    epochs = [r['epoch'] for r in logs]; tr_loss = [r['train_loss'] for r in logs]; va_loss = [r['val_loss'] for r in logs]; tr_acc = [r['train_acc'] for r in logs]; va_acc = [r['val_acc'] for r in logs]
    plt.figure(figsize=(12,4)); plt.subplot(1,2,1); plt.plot(epochs, tr_loss, label='train_loss'); plt.plot(epochs, va_loss, label='val_loss'); plt.xlabel('epoch'); plt.ylabel('loss'); plt.title('Train / Val Loss'); plt.legend(); plt.grid(True, alpha=0.3)
    plt.subplot(1,2,2); plt.plot(epochs, tr_acc, label='train_acc'); plt.plot(epochs, va_acc, label='val_acc'); plt.xlabel('epoch'); plt.ylabel('acc'); plt.title('Train / Val Accuracy'); plt.legend(); plt.grid(True, alpha=0.3)
    plt.tight_layout(); plt.savefig(save_dir / 'curves_train_val.png', dpi=180, bbox_inches='tight'); plt.close()

def plot_final_summary(metrics: dict, save_dir: Path):
    names = ['train','val','test']; losses = [metrics[n]['loss'] for n in names]; accs = [metrics[n]['acc'] for n in names]
    plt.figure(figsize=(10,4)); plt.subplot(1,2,1); plt.bar(names, losses); plt.ylabel('loss'); plt.title('Final Best-Model Loss by Split'); plt.grid(True, axis='y', alpha=0.3)
    plt.subplot(1,2,2); plt.bar(names, accs); plt.ylabel('acc'); plt.title('Final Best-Model Accuracy by Split'); plt.grid(True, axis='y', alpha=0.3)
    plt.tight_layout(); plt.savefig(save_dir / 'summary_train_val_test.png', dpi=180, bbox_inches='tight'); plt.close()

@torch.no_grad()
def export_representative_images(model: nn.Module, recs: list, idx_to_class, save_dir: Path, device: torch.device):
    """每类导出 3 张代表图：优先预测正确且对真实类别置信度最高。"""
    model.eval(); out_root = save_dir / 'representative_images'; out_root.mkdir(parents=True, exist_ok=True)
    class_items = sorted((int(k), v) for k, v in idx_to_class.items()) if isinstance(idx_to_class, dict) else list(enumerate(idx_to_class))
    mean, std = float(MEAN[0] if isinstance(MEAN, (list, tuple)) else MEAN), float(STD[0] if isinstance(STD, (list, tuple)) else STD)
    correct_pool, fallback_pool = ({k: [] for k,_ in class_items}, {k: [] for k,_ in class_items})
    for rec in recs:
        img = Image.open(rec.path).convert('L').resize((INPUT_SIZE, INPUT_SIZE)); arr = np.asarray(img, dtype=np.float32) / 255.0
        x = torch.from_numpy(arr).unsqueeze(0).unsqueeze(0); x = (x - mean) / std; x = x.to(device, non_blocking=True)
        logits, _ = model(x, need_aux=False); prob = torch.softmax(logits, dim=1)[0]; pred = int(prob.argmax().item()); true_score = float(prob[rec.label].item())
        item = {'path': Path(rec.path), 'score': true_score, 'pred': pred}; fallback_pool[rec.label].append(item)
        if pred == rec.label: correct_pool[rec.label].append(item)
    summary = {}
    for label, class_name in class_items:
        cls_dir = out_root / class_name; cls_dir.mkdir(parents=True, exist_ok=True)
        selected, used = [], set(); correct_sorted = sorted(correct_pool[label], key=lambda z: z['score'], reverse=True); fallback_sorted = sorted(fallback_pool[label], key=lambda z: z['score'], reverse=True)
        for pool in (correct_sorted, fallback_sorted):
            for item in pool:
                if len(selected) >= REPR_PER_ACTION: break
                p = str(item['path'])
                if p not in used: selected.append(item); used.add(p)
        summary[class_name] = []
        for rank, item in enumerate(selected, start=1):
            pred_name = dict(class_items).get(item['pred'], str(item['pred'])); dst = cls_dir / f'{rank:02d}_score_{item["score"]:.4f}_pred_{pred_name}_{item["path"].name}'
            shutil.copy2(item['path'], dst)
            summary[class_name].append({'rank': rank, 'src': str(item['path']), 'saved_as': str(dst), 'true_class': class_name, 'pred_class': pred_name, 'true_class_score': round(item['score'], 6)})
    with open(out_root / 'representative_summary.json', 'w', encoding='utf-8') as f: json.dump(summary, f, ensure_ascii=False, indent=2)
    print(f'代表性TR图已导出到: {out_root}')

# ==== 8) 主流程 ====
def main():
    seed_all(); SAVE_DIR.mkdir(parents=True, exist_ok=True)
    print(f'数据根目录: {DATA_ROOT}')
    print(f'随机种子 SPLIT_SEED = {SPLIT_SEED}')
    print(f'BATCH_SIZE={BATCH_SIZE}  NUM_WORKERS={NUM_WORKERS}  AMP={USE_AMP}')

    train_recs, val_recs, test_recs, c2i, i2c, split_brief = scan_records(DATA_ROOT)
    num_classes = len(c2i)
    print(f'类别数: {num_classes}')
    print(f'samples -> train/val/test = {len(train_recs)}/{len(val_recs)}/{len(test_recs)}')

    split_meta = {
        'rule': 'use all images in each action_person folder, deterministic shuffle, then split by 18:4:3 ratio',
        'split_seed': SPLIT_SEED,
        'train_ratio': TRAIN_RATIO,
        'val_ratio': VAL_RATIO,
        'test_ratio': TEST_RATIO,
        'raw2cls': RAW2CLS,
        'class_order': CLASS_ORDER,
        'split_brief': split_brief,
    }
    with open(SAVE_DIR / 'split_meta.json', 'w', encoding='utf-8') as f:
        json.dump(split_meta, f, ensure_ascii=False, indent=2)
    with open(SAVE_DIR / 'class_to_idx.json', 'w', encoding='utf-8') as f:
        json.dump(c2i, f, ensure_ascii=False, indent=2)

    common_loader_args = dict(
        batch_size=BATCH_SIZE,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=(PERSISTENT_WORKERS and NUM_WORKERS > 0),
    )
    if NUM_WORKERS > 0:
        common_loader_args['prefetch_factor'] = PREFETCH_FACTOR

    train_loader = DataLoader(TRDataset(train_recs, train=True,  use_thr=True),  shuffle=True,  **common_loader_args)
    val_loader   = DataLoader(TRDataset(val_recs,   train=False, use_thr=False), shuffle=False, **common_loader_args)
    test_loader  = DataLoader(TRDataset(test_recs,  train=False, use_thr=False), shuffle=False, **common_loader_args)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'device = {device}')
    if torch.cuda.is_available():
        print(f'GPU数量 = {torch.cuda.device_count()}')
        for i in range(torch.cuda.device_count()):
            print(f'  GPU{i}: {torch.cuda.get_device_name(i)}')

    model = radar_nn1(num_classes)
    if USE_DATA_PARALLEL and torch.cuda.device_count() > 1:
        model = nn.DataParallel(model)
        print('[并行] 已启用 nn.DataParallel')
    model = model.to(device)

    criterion = nn.CrossEntropyLoss(weight=build_class_weights(train_recs, num_classes).to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
    scaler = torch.amp.GradScaler('cuda', enabled=(device.type == 'cuda' and USE_AMP))

    best_val_acc, bad_epochs, logs = -1.0, 0, []
    ckpt_path = SAVE_DIR / 'radar_nn1_4class(v2)_best.pth'

    for epoch in range(1, EPOCHS + 1):
        train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, scaler, criterion, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)
        scheduler.step()

        row = {
            'epoch': epoch,
            'train_loss': train_loss,
            'train_acc': train_acc,
            'val_loss': val_loss,
            'val_acc': val_acc,
            'lr': optimizer.param_groups[0]['lr'],
        }
        logs.append(row)
        print(f"Epoch {epoch:03d}/{EPOCHS:03d} | train {train_loss:.4f}/{train_acc:.4f} | val {val_loss:.4f}/{val_acc:.4f} | lr={row['lr']:.6f}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            bad_epochs = 0
            save_checkpoint(ckpt_path, model, c2i, i2c, split_meta)
            print(f'[保存] {ckpt_path}')
        else:
            bad_epochs += 1
            if bad_epochs >= PATIENCE:
                print(f'[早停] 连续 {PATIENCE} 个 epoch 验证集未提升。')
                break

    with open(SAVE_DIR / 'train_log.json', 'w', encoding='utf-8') as f:
        json.dump(logs, f, ensure_ascii=False, indent=2)
    plot_curves(logs, SAVE_DIR)

    state = torch.load(ckpt_path, map_location=device)
    unwrap_model(model).load_state_dict(state['model_state'])

    final_metrics = {}
    for name, loader in [('train', train_loader), ('val', val_loader), ('test', test_loader)]:
        loss, acc = evaluate(model, loader, criterion, device)
        final_metrics[name] = {'loss': loss, 'acc': acc}
        print(f'[Final {name}] loss={loss:.4f}, acc={acc:.4f}')

    plot_final_summary(final_metrics, SAVE_DIR)
    export_representative_images(
        model,
        {'train': train_recs, 'val': val_recs, 'test': test_recs}[REPR_FROM_SPLIT],
        i2c, SAVE_DIR, device
    )

    try:
        core = unwrap_model(model).eval()
        example = torch.randn(1, 1, INPUT_SIZE, INPUT_SIZE, device=device)
        class Wrapped(nn.Module):
            def __init__(self, m):
                super().__init__(); self.m = m
            def forward(self, x):
                return self.m(x, need_aux=False)[0]
        scripted = torch.jit.trace(Wrapped(core).to(device), example)
        scripted.save(str(SAVE_DIR / 'radar_nn1_4class_v2_scripted.pt'))
        print(f"[导出] {SAVE_DIR / 'radar_nn1_4class_v2_scripted.pt'}")
    except Exception as e:
        print(f'[警告] TorchScript 导出失败: {e}')

    summary = {
        'data_root': str(DATA_ROOT),
        'save_dir': str(SAVE_DIR),
        'num_classes': num_classes,
        'best_val_acc': best_val_acc,
        'final_metrics': final_metrics,
        'batch_size': BATCH_SIZE,
        'num_workers': NUM_WORKERS,
        'split_rule': split_meta['rule'],
        'class_order': CLASS_ORDER,
        'raw2cls': RAW2CLS,
    }
    with open(SAVE_DIR / 'summary.json', 'w', encoding='utf-8') as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print('\n已保存：')
    print(f'  - {SAVE_DIR / "radar_nn1_4class(v2)_best.pth"}')
    print(f'  - {SAVE_DIR / "radar_nn1_4class_v2_scripted.pt"}（若导出成功）')
    print(f'  - {SAVE_DIR / "train_log.json"}')
    print(f'  - {SAVE_DIR / "curves_train_val.png"}')
    print(f'  - {SAVE_DIR / "summary_train_val_test.png"}')
    print(f'  - {SAVE_DIR / "summary.json"}')

if __name__ == '__main__':
    main()